<?php

namespace App\DataFixtures;

use App\Entity\Category;
use App\Entity\Character;
use App\Entity\Mythologie;
use Cocur\Slugify\Slugify;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Persistence\ObjectManager;

class CharacterFixtures extends Fixture implements DependentFixtureInterface
{
    public const CHARACTERS = [
        [
            'name' => 'Zeus',
            'description' => 'Dieu de la Foudre et maître de l\'Olympe',
            'picture' => 'https://www.dol-celeb.com/wp-content/uploads/2015/04/zeus.jpg',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Arthémis',
            'description' => 'Déesse de la chasse et de la nature sauvage',
            'picture' => 'http://www.chevreriedartemis.fr/images/artemis_1.jpg',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Arès',
            'description' => 'Dieu de la guerre offensive ',
            'picture' => 'https://static.wikia.nocookie.net/creer-votre-mythologie/images/3/34/9b3780dca496789d1ab19c679d84cfa9.jpg/revision/latest?cb=20200805233823&path-prefix=fr',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Hadès',
            'description' => 'Dieu du royaume des morts',
            'picture' => 'https://www.tigrisleonum.com/wp-content/uploads/2021/09/DMyd6biVoAAfnKB.jpg',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Poséïdon',
            'description' => 'Dieu des mers et océans',
            'picture' => 'https://i.pinimg.com/originals/06/ff/50/06ff50672550a91e2b8afcb3cfac85a1.jpg',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Athéna',
            'description' => 'Déesse de la guerre defensive et de la sagesse',
            'picture' => 'https://nordactu.fr/wp-content/uploads/2021/05/Lhistoire-fascinante-dAthena-deesse-grecque-de-la-sagesse.jpg',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Héphaïstos',
            'description' => 'Dieu forgeron du feu et des volcans',
            'picture' => 'https://static.wikia.nocookie.net/percy-jackson/images/c/c4/Hephaistos.jpg/revision/latest?cb=20160709145113&path-prefix=fr',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Aphrodite',
            'description' => 'Déesse de l\'amour et du désir et de la beauté',
            'picture' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTULV08B7SHT2I_KOWnGq_Yoa9jMOGuJvmJWQ&usqp=CAU',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Apolon',
            'description' => 'dieu grec des arts, du chant, de la musique, de la beauté masculine, de la poésie et de la lumière.',
            'picture' => 'https://static.wikia.nocookie.net/mythologie-grecoromaine/images/8/82/Apollon.jpg/revision/latest?cb=20160209222257&path-prefix=fr',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Dionysos',
            'description' => 'dieu du vin, des fêtes, de l\'extase et du délire',
            'picture' => 'https://i1.sndcdn.com/artworks-000491415330-05shh0-t500x500.jpg',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Héra',
            'description' => 'déesse du mariage et de la fécondité',
            'picture' => 'http://ekladata.com/LlaelGqAToTZKEHVvvzxbrF-Rd0.jpg',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Hestia',
            'description' => 'divinité du feu sacré et du foyer',
            'picture' => 'https://static.wikia.nocookie.net/heros/images/a/ac/Hestia_Infobox.jpg/revision/latest/top-crop/width/360/height/450?cb=20210109165610&path-prefix=fr',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Déméter',
            'description' => 'déesse de la terre fertile',
            'picture' => 'https://montresjrey.com/wp-content/uploads/2018/04/Demeter.jpg',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Hermès',
            'description' => 'dieu du voyage, guide des âmes au royaume des morts et messager de Zeus ',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Ananké',
            'description' => 'déesse de l\'inévitable, de la compulsion et de la nécessité.',
            'picture' => 'https://scontent-cdt1-1.xx.fbcdn.net/v/t1.6435-9/fr/cp0/e15/q65/92740130_3546650535361311_5819163872665272320_n.jpg?_nc_cat=109&ccb=1-5&_nc_sid=e007fa&_nc_ohc=2it54IWxIWoAX-Eb7hx&_nc_ht=scontent-cdt1-1.xx&oh=00_AT-NsWmB4EpJvEiRi4fSQddKSVYq6i_FMNPC1Ruj7uZaPA&oe=622ED615',
                          https://static.wikia.nocookie.net/creer-votre-mythologie/images/3/34/9b3780dca496789d1ab19c679d84cfa9.jpg/revision/latest?cb=20200805233823&path-prefix=fr
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Chaos',
            'description' => 'entité primordial, la première à être apparue.',
            'picture' => 'http://engelmickael.free.fr/chaos.jpeg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Chronos',
            'description' => 'dieu du temps',
            'picture' => 'https://i.skyrock.net/5484/89135484/pics/3181220899_1_2_R4uRow1F.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Erèbe',
            'description' => 'dieu des ténèbres',
            'picture' => 'https://static.wikia.nocookie.net/percy-jackson/images/9/90/Erebe.jpg/revision/latest/scale-to-width-down/330?cb=20180630174941&path-prefix=fr',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Eros',
            'description' => 'dieu de l\'amour et de l\'acte sexuel',
            'picture' => 'https://cdnb.artstation.com/p/assets/images/images/023/093/839/large/john-matthew-nanoz-eros2020.jpg?1578062874',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Ether',
            'description' => 'dieu de la lumière céleste',
            'picture' => 'https://i.ytimg.com/vi/YFTfddztJc8/hqdefault.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Gaïa',
            'description' => 'déesse de la terre',
            'picture' => 'https://static.wikia.nocookie.net/percy-jackson/images/3/3e/Gaia.jpg/revision/latest/top-crop/width/360/height/450?cb=20130922131235&path-prefix=fr',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Héméra',
            'description' => 'déesse de la lumière terrestre et personnification du jour',
            'picture' => 'https://ae01.alicdn.com/kf/HTB1wSFjSpXXXXXxXXXXq6xXFXXXr.jpg?size=75014&height=900&width=696&hash=bdecddbbc6fc22e1d2110e9eceea699e',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Hypnos',
            'description' => 'dieu du sommeil',
            'picture' => 'https://d.furaffinity.net/art/-ashes-/1637337454/1637337454.-ashes-_%D0%B3%D0%B8%D0%BF%D0%BD%D0%BE_%D0%B1%D0%B5%D0%B7.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Moros',
            'description' => 'dieu du destin fatal ou de la mort brutale',
            'picture' => 'https://i.pinimg.com/564x/80/51/67/8051676eda14246d470a4e0eeadee319--pai-tempo.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Nèsoi',
            'description' => 'Déesse des îles',
            'picture' => 'https://cdnb.artstation.com/p/assets/images/images/044/164/537/large/mordrenn-doret-mordrenn-doret-deesse-grec-nesoi.jpg?1639267807',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Nyx',
            'description' => 'divinité de la nuit',
            'picture' => 'http://ekladata.com/QD3_Qp6_B04MdPsCNv2CO9oIXvE.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Ouranos',
            'description' => 'dieu des cieux',
            'picture' => 'https://static.wikia.nocookie.net/percy-jackson/images/8/89/Ouranos.jpg/revision/latest?cb=20130901164152&path-prefix=fr',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Phanès',
            'description' => 'dieu de la procréation',
            'picture' => 'https://pbs.twimg.com/media/C9dTTKTWAAAH6lo.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Pontos',
            'description' => 'divinité de la mer',
            'picture' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxNtkrXRe-U2IEsTETknHKXGaLH1YDHOKwYg&usqp=CAU',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Tartare',
            'description' => 'dieu de la partie la plus sombre et la plus profonde des enfers',
            'picture' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTznOtIyrGRtSZ_x1WOGaHRrzXkJpeAAm6TA&usqp=CAU',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Thalassa',
            'description' => 'esprit de la mer et dieu des profondeurs',
            'picture' => 'https://scontent-cdg2-1.xx.fbcdn.net/v/t1.6435-9/56337117_2102697436446215_4574146522496630784_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=9267fe&_nc_ohc=W61IftcePbQAX-C87X6&_nc_ht=scontent-cdg2-1.xx&oh=00_AT9Hah7LYfkEbm-7Qm1K3YzWbwsTRh65Ky5uguHvnej3Ww&oe=622FA451',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Thanatos',
            'description' => 'dieu de la mort',
            'picture' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRw2QeWzwxuQG53dOkevmV418hvg6pSBKvEOQ&usqp=CAU',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Athos',
            'description' => 'dieu de la montagne Athos',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Cithéron',
            'description' => 'dieu de la montagne Cithéron',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Dicté',
            'description' => 'déesse de la montagne Dicté',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Etna',
            'description' => 'déesse du Volcan Etna',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Hélicon',
            'description' => 'dieu de la montagne Hélicon',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Ida crétois',
            'description' => 'dieu de la montagne Ida crétois',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Ida phrygien',
            'description' => 'dieu de la montagne Ida phrygien',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Laurion',
            'description' => 'dieu de la montagne Laurion',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Nysos',
            'description' => 'dieu de la montagne Nysos',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Olympe',
            'description' => 'dieu de l\'Olympe',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Orthrys',
            'description' => 'dieu de la montagne Orthrys',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Parnasse',
            'description' => 'dieu de la montagne Parnasse',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Tmolos',
            'description' => 'dieu de la montagne Tmolos',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Dieu primordiale',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Céos',
            'description' => 'Titan de l\'intellect et des constellations',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Crios',
            'description' => 'Titan de l\'astronomie',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Hypérion',
            'description' => 'Titan de la lumière',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Japet',
            'description' => 'Titan de la mortalité et de l\'Ouest',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Mnémosyne',
            'description' => 'Titanide de la mémoire et du souvenir',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Océan',
            'description' => 'Titan des fleuves, de la mer et des océans',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Phébé',
            'description' => 'Titanide de l\'intellect et des prophéties,',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Rhéa',
            'description' => 'Titanide de la fertilité, de la maternité et des animaux',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Téthys',
            'description' => 'Titanide de l\'eau, des rivières et des sources',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Théia',
            'description' => 'Titanide de la vue et de la lumière brillante du ciel bleu',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Thémis',
            'description' => 'Titanide de l\'ordre, de la loi et de la justice',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Asia',
            'description' => 'Titanide du renom, de la gloire et de l\'infamie',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Asthéria',
            'description' => 'Titanide des oracles nocturnes et des étoiles filantes',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Astréos',
            'description' => 'Titan du crépuscule, des étoiles, des planètes et de l\'astrologie',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Atlas',
            'description' => 'Titan contraint par Zeus de porter le ciel sur ses épaules',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Aura',
            'description' => 'Titanide de la brise et de l\'air frais du petit matin.',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Dioné',
            'description' => 'Titanide de l\'oracle de Dodone',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Dios',
            'description' => 'Titanide de l\'aurore',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Epiméthée',
            'description' => 'Titan des pensées après coup',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Eurybie',
            'description' => 'Titanide de la maîtrise des mers',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Eurynomé',
            'description' => 'Titanide des prairies et des pâturages',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Elios',
            'description' => 'Titan du soleil et gardien des serments',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Lélantos',
            'description' => 'Titan de l\'air et de la traque',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Léto',
            'description' => 'Titanide de la maternité',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Ménétios',
            'description' => 'Titan de la colère violente, de l\'action brusque et de la mortalité humaine',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Métis',
            'description' => 'Titanide du bon conseil, des avis, de la préparation, de la ruse et de la sagesse',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Ophion',
            'description' => 'dans certaines versions du mythe, il règne sur la Terre avec Eurynomé avant que Cronos ne le renverse ; une autre version le décrit comme un serpent né de l\'Œuf du monde',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Pallas',
            'description' => 'Titan de l\'art de la guerre',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Persès',
            'description' => 'Titan de la destruction et de la paix',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Prométhée',
            'description' => 'Titan de la préméditation et du conseil avisé, et de la prévoyance',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Séléné',
            'description' => 'Titanide de la lune',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Styx',
            'description' => 'Océanide et Titanide de la rivière Styx, personnification de la haine',
            'picture' => 'http://pm1.narvii.com/7108/532ba17c5b6a1a532612b018cdc6e20a4fbb05a9r1-450-637v2_uhq.jpg',
            'category' => 'Titan',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Agrios',
            'description' => 'Géant thrace mangeur d\'homme, mi-homme, mi-ours',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Alcyonée',
            'description' => 'aîné des géants de Thrace',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Otos',
            'description' => 'Un des géants jumeaux (Aloades) ayant tenté de prendre d\'assaut les cieux',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Ephialtès',
            'description' => 'Un des géants jumeaux (Aloades) ayant tenté de prendre d\'assaut les cieux',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Antée',
            'description' => 'Géant libyen défiant à la lutte jusqu\'à la mort tous les visiteurs',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Argos Panoptès',
            'description' => ' Géant aux cent yeux, gardant Io',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Encelade',
            'description' => 'Géant de Thrace enterré sous le mont Etna',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Gègenées',
            'description' => 'tribut de géants de Thrace à six bras habitant la montagne de l\'our en Mysie',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Géryon',
            'description' => 'Géant à trois corps et quatre ailes',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Antiphatès',
            'description' => 'roi des géants Lesrygons',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Orion',
            'description' => 'Chasseur géant',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Porphyrion',
            'description' => 'roi des géants de Thrace',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Talos',
            'description' => 'géant forgé de bronze gardien de Europe',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Tityos',
            'description' => 'Géant, bâtard de Zeus avec Elara',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Alcyonée',
            'description' => 'aîné des géants de Thrace',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Typhon',
            'description' => 'Le père des monstres le seul ayant conquis l\'Olympe',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Alpos',
            'description' => 'monstre géant avec cent têtes de vipère',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Damasène',
            'description' => 'Guerrier géant',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Damysos',
            'description' => 'Le plus rapide des géants',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Argès',
            'description' => 'L\'un des trois Cyclopes forgé par les trois dieux principaux de l\'Olympe',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Brontès',
            'description' => 'L\'un des trois Cyclopes forgé par les trois dieux principaux de l\'Olympe',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Steropès',
            'description' => 'L\'un des trois Cyclopes forgé par les trois dieux principaux de l\'Olympe',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Polyphème',
            'description' => 'Cyclope berger sur une île de Sicile',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Elatréus',
            'description' => 'Cyclope à la force exeptionnelle',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Euryalos',
            'description' => 'Redoutable guerrier cyclope',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Trachios',
            'description' => 'le rude cyclope',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Halimédès',
            'description' => 'Le monstrueux cyclope',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Briarée',
            'description' => 'Le plus redoutable des Hécatonchires',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Cottos',
            'description' => 'hécatonchire',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Gygès',
            'description' => 'hécatonchire',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Aigle du Cocasse',
            'description' => 'Célèbre rapace sous les odre de Zeus',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Amalthée',
            'description' => 'Chèvre ayant nouri Zeus petit',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Biche de Cérynie',
            'description' => 'Cervidé cornue à la stature de taureau consacré à Arthémis',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Campé',
            'description' => 'Monstre à corps de femme recouvert d\'écailles sur le bas, une chevelure hérissée de serpents venimeux et un scorpion se déplaçant sur ses épaules, ainsi qu\'une ceinture de bête sauvages parmi lesquels sont un ours, un lion, etc.',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Dinos',
            'description' => 'Une des juments anthropophage dont la sauvagerie et la vigueur était inouï',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Lampon',
            'description' => 'Une des juments anthropophage dont la sauvagerie et la vigueur était inouï',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Podargos',
            'description' => 'Une des juments anthropophage dont la sauvagerie et la vigueur était inouï',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Xanthos',
            'description' => 'Une des juments anthropophage dont la sauvagerie et la vigueur était inouï',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Lampos',
            'description' => 'Un des chevaux tirant le char du soleil, éblouissant midi ou resplendissant',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Actéon',
            'description' => 'Un des chevaux tirant le char du soleil, aube rayonnante ou le lumineux',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Chronos',
            'description' => 'Un des chevaux tirant le char du soleil, Le temps',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Astérope',
            'description' => 'Un des chevaux tirant le char du soleil, Yeux étoilés',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Bronté',
            'description' => 'Un des chevaux tirant le char du soleil, Tonnerre',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Pyrois',
            'description' => 'Un des chevaux tirant le char du soleil, emflammé',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Érythrée',
            'description' => 'Un des chevaux tirant le char du soleil, Soleil levant ou le rouge',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Phlégon',
            'description' => 'Un des chevaux tirant le char du soleil, Soleil couchant ou qui aime la Terre',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Éuos',
            'description' => 'Un des chevaux tirant le char du soleil, de l\'orient',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Ethion',
            'description' => 'Un des chevaux tirant le char du soleil, Fougueux rouge',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Centoros',
            'description' => 'Un des chevaux tirant le char du soleil',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Chiron',
            'description' => 'Un des chevaux tirant le char du soleil',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Eurytion',
            'description' => 'Un des chevaux tirant le char du soleil',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Hyléos',
            'description' => 'Un des chevaux tirant le char du soleil',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Nessos',
            'description' => 'Un des chevaux tirant le char du soleil',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Pholos',
            'description' => 'Un des chevaux tirant le char du soleil',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Rhoécos',
            'description' => 'Un des chevaux tirant le char du soleil',
            'picture' => 'https://cdn.shopify.com/s/files/1/0076/6987/4778/files/typhon-mythologie-grecque-dragon-naga_b7998197-70c8-483c-b7f8-7d72924d453c.jpg?v=1608335860',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Cerbere',
            'description' => 'Le chien gardien de enfer à trois têtes',
            'picture' => 'https://m.media-amazon.com/images/I/71qzN7s0bsL._AC_SX425_.jpg',
            'category' => 'Creature',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Achille',
            'description' => 'Le héros légendaire de Grèce ayant pour seule point faible sa cheville',
            'picture' => 'https://i.pinimg.com/236x/3a/e6/e3/3ae6e3944c9a8e9c61eca572a9cbbc6d.jpg',
            'category' => 'Heros',
            'mythology' => 'Grecque',
        ],
        [
            'name' => 'Rê',
            'description' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Re-Horakhty.svg/langfr-180px-Re-Horakhty.svg.png',
            'picture' => 'Dieu du soleil ',
            'category' => 'Dieu',
            'mythology' => 'Egyptienne',
        ],
        [
            'name' => 'Isis',
            'description' => 'Deesse du ciel',
            'picture' => 'https://www.dol-celeb.com/wp-content/uploads/2020/07/isis.jpg',
            'category' => 'Dieu',
            'mythology' => 'Egyptienne',
        ],
        [
            'name' => 'Anubis',
            'description' => 'Dieu de la mort',
            'picture' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Anubis_standing.svg/langfr-250px-Anubis_standing.svg.png',
            'category' => 'Dieu',
            'mythology' => 'Egyptienne',
        ],
        [
            'name' => 'Osiris',
            'description' => 'Dieu Roi du monde',
            'picture' => 'https://mythologica.fr/egypte/pic/osiris.png',
            'category' => 'Dieu',
            'mythology' => 'Egyptienne',
        ],
        [
            'name' => 'Bastet',
            'description' => 'Deesse de la joie du foyer',
            'picture' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Bastet.svg/1200px-Bastet.svg.png',
            'category' => 'Dieu',
            'mythology' => 'Egyptienne',
        ],
        [
            'name' => 'Odin',
            'description' => 'Dieu principal de la mythologie nordique',
            'picture' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Odin_%28Manual_of_Mythology%29.jpg/1200px-Odin_%28Manual_of_Mythology%29.jpg',
            'category' => 'Dieu',
            'mythology' => 'Nordique',
        ],
        [
            'name' => 'Thor',
            'description' => 'Dieu du Tonnerre',
            'picture' => 'https://static.blog4ever.com/2015/01/793370/artfichier_793370_7661821_201804082647356.jpg',
            'category' => 'Dieu',
            'mythology' => 'Nordique',
        ],
        [
            'name' => 'Fenrir',
            'description' => 'Loup geant fils de lokir et de Angrboda',
            'picture' => 'https://cdn.shopify.com/s/files/1/2795/4706/articles/fenrir_700x.png?v=1635170415',
            'category' => 'Creature',
            'mythology' => 'Nordique',
        ],
        [
            'name' => 'Jörmungandr',
            'description' => 'Serpent monde',
            'picture' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-7va8rhXNrladjtXOmHYtAhN5wbLQH69yZpVFSz5RSrp3ZvNuPbuLfIwPg6e5PrzGCzc&usqp=CAU',
            'category' => 'Creature',
            'mythology' => 'Nordique',
        ],
        [
            'name' => 'Hel',
            'description' => 'Deesse des morts',
            'picture' => 'https://cdn.shopify.com/s/files/1/2392/8713/files/deesse-hell.jpg?v=1569514449',
            'category' => 'Dieu',
            'mythology' => 'Nordique',
        ],
        [
            'name' => 'Dieu',
            'description' => 'Createur de la Terre',
            'picture' => 'https://static.cnews.fr/sites/default/files/styles/image_640_360/public/point1.jpg?itok=jGTH8XuS',
            'category' => 'Dieu',
            'mythology' => 'Biblique',
        ],
        [
            'name' => 'Behemoth',
            'description' => 'Une des bête de l\'apocalypse bête à tête de taureau reignant sur la terre',
            'picture' => 'https://static.wikia.nocookie.net/revari/images/b/bb/Behemoth_-_Donnerbehemoth.jpg/revision/latest/top-crop/width/360/height/450?cb=20180106194747&path-prefix=de',
            'category' => 'Creature',
            'mythology' => 'Biblique',
        ],
        [
            'name' => 'Leviathan',
            'description' => 'Une des bête de l\'apocalypse bête reignant sur les mers',
            'picture' => 'http://ekladata.com/k4AsNSh9ieQXYEx1-Azs3RY7bwQ@200x200.jpg',
            'category' => 'Creature',
            'mythology' => 'Biblique',
        ],
        [
            'name' => 'Moïse',
            'description' =>'Prophète ayant sauvé les hébreux de l\'esclavage des egyptiens',
            'picture' => 'https://www.chretiensaujourdhui.com/asset/uploads/2014/11/Moise.jpg',
            'category' => 'Heros',
            'mythology' => 'Biblique',
        ],
        [
            'name' => 'Samson',
            'description' => 'Héros biblique tirant sa puissance d\'un de ses cheveux',
            'picture' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Leighton-Samson-c._1858.jpg/240px-Leighton-Samson-c._1858.jpg',
            'category' => 'Heros',
            'mythology' => 'Biblique',
        ],
        [
            'name' => 'Taranis',
            'description' => 'dieu du ciel',
            'picture' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVGzql7zLtUfx5fJjiVdVwd-39QZZCinPg_g&usqp=CAU',
            'category' => 'Dieu',
            'mythology' => 'Celtique',
        ],
        [
            'name' => 'Esus',
            'description' => 'dieu batisseur',
            'picture' => 'https://static.blog4ever.com/2015/01/793370/artfichier_793370_4485093_201501254637730.jpg',
            'category' => 'Dieu',
            'mythology' => 'Celtique',
        ],
        [
            'name' => 'Fomoires',
            'description' => 'demi-dieu inhumain et d\'une puissance colosal',
            'picture' => 'https://static.blog4ever.com/2008/02/182076/artfichier_182076_5050821_201508131737986.jpg',
            'category' => 'Creature',
            'mythology' => 'Celtique',
        ],
        [
            'name' => 'Banshee',
            'description' => 'Créature fantomatique dont on dit que le crie peut tuer de trouille une vingtaine homme',
            'picture' => 'https://static.wikia.nocookie.net/teenwolf/images/8/89/Banshee.jpg/revision/latest?cb=20130730154245&path-prefix=fr',
            'category' => 'Creature',
            'mythology' => 'Celtique',
        ],
        [
            'name' => 'Dorminus',
            'description' => 'Dieu du printemps chaud',
            'picture' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Dominus_Rincaleus.jpg/220px-Dominus_Rincaleus.jpg',
            'category' => 'Heros',
            'mythology' => 'Celtique',
        ],
        [
            'name' => 'Izanami',
            'description' => 'déesse de la création et de la mort',
            'picture' => 'https://m.media-amazon.com/images/I/714Q-U7IyYL._AC_SY679_.jpg',
            'category' => 'Dieu',
            'mythology' => 'Japonaise',
        ],
        [
            'name' => 'Izanagi',
            'description' => 'Dieu du shintoïsme co-créateur du monde',
            'picture' => 'https://i.pinimg.com/474x/fd/52/39/fd5239432cb1ffe45c0e21da84ba2c1c--japanese-mythology-japanese-folklore.jpg',
            'category' => 'Dieu',
            'mythology' => 'Japonaise',
        ],
        [
            'name' => 'Akabeko',
            'description' => 'une vache rouge batisseuse de temple',
            'picture' => 'https://www.tokyo-smart.com/5199-large_default/akabeko.jpg',
            'category' => 'Creature',
            'mythology' => 'Japonaise',
        ],
        [
            'name' => 'Akurojin-no-hi',
            'description' => 'flamme spectrale du dieu du feu ',
            'picture' => 'https://i.pinimg.com/170x/be/6d/2c/be6d2ce8d2a8dba4e8b84c525357cde2.jpg',
            'category' => 'Creature',
            'mythology' => 'Japonaise',
        ],
        [
            'name' => 'Susanô',
            'description' => 'Dieu des tempètes et des valeurs',
            'picture' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2Cnti0HfAO1K5JrHbE05NFepMIfigMWLOhg&usqp=CAU',
            'category' => 'Dieu',
            'mythology' => 'Japonaise',
        ],
    ];
    public function load(ObjectManager $manager): void
    {
        // $product = new Product();
        // $manager->persist($product);
        foreach (self::CHARACTERS as $character) {
            $category = $manager
            ->getRepository(Category::class)
            ->findOneBy(array('Name' => $character['category']));
            ;
            $mythology = $manager
                ->getRepository(Mythologie::class)
                ->findOneBy(['name' => $character['mythology']])
            ;
            $characterEntity = new Character();
            $characterEntity->setName($character['name']);
            $characterEntity->setDescription($character['description']);
            $characterEntity->setPicture($character['picture']);
            $characterEntity->setCategory($category);
            $characterEntity->setMythology($mythology);
            $slug = new Slugify();
            $characterEntity->setSlug($slug->slugify($character['name']));

            $manager->persist($characterEntity);
            $manager->flush();
        }
    }    
    public function getDependencies()
    {
        return [
            CategoryFixtures::class,
            MythologieFixtures::class,
        ];
    }
}
